name: 🚀 Deploy website on server
on:
  push:
    branches:
      
main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    
name: 🚚 Get latest code
    uses: actions/checkout@v2
name: Install Dependencies Node
  run: npm install
name: Build tailwindcss
run: npm run build
name: 📂 Sync files
uses: SamKirkland/FTP-Deploy-Action@4.2.0
with:
  server: ${{ secrets.FTP_SERVER }}
  username: ${{ secrets.FTP_USERNAME }}
  password: ${{ secrets.FTP_PASSWORD }}
